<h1 class="text-center">A propos de MyWishList</h1></br>

<h2 class="text-center">MyWishList</h2><br>
<p class="text-justify">
    MyWishList est une application en ligne pour créer, partager et gérer des listes de cadeaux.
    L'application permet à un utilisateur de créer une liste de souhaits à l'occasion d'un événement
    particulier (anniversaire, fin d'année, mariage, retraite …) et lui permet de diffuser cette liste de
    souhaits à un ensemble de personnes concernées. Ces personnes peuvent alors consulter cette liste
    et s'engager à offrir 1 élément de la liste. Cet élément est alors marqué comme réservé dans cette
    liste.
</p>

<h2 class="text-center">Fonctionnalités</h2><br>
<p class="text-justify">
    Pour créer une liste d'envie, il faut être inscrit sur le site et connecté à votre compte. Par la suite,
    vous pourrez créer une ou plusieurs liste, en y ajoutant un ou plusieurs objets selon vos envies.
    Cette liste peut être à tout moment modifiée dès lors que la date d'expiration de celle-ci n'est pas dépassée,
    il en est de même pour les produits qui la compose.<br><br>
    Une fois la liste créer, tout utilisateur du site peut réserver un produit d'une liste (qui ne lui appartient pas)
    et ajouter un message avec sa réservation, de ce fait, le produit est réservé et ne peut plus être modifié ou
    supprimé par le créateur de la liste. Il est également possible d'écrire un message publique sur une liste (messages
    qui seront affichés en bas de page d'une liste).<br><br>
    Une fois la date d'expiration de la liste dépassée, le créateur de la liste a accès au nom et message des personnes
    ayant réservé des produits de sa liste.
</p>
<br>

<div class="card bottom">
    <h1 class="card-title text-center mb-0">Contributeurs</h1>
    <div class="card-body">
        <h5 class="text-center">Julien Noël - <a href="https://github.com/juliennoel9">GitHub</a></h5>
        <h5 class="text-center">Louis Demange - <a href="https://github.com/Nekzuris">GitHub</a></h5>
        <h5 class="text-center">Loïck Nosal - <a href="https://github.com/LoickNosal">GitHub</a></h5>
        <h5 class="text-center">Paul Gsell - <a href="https://github.com/poluxtobee">GitHub</a></h5>
        <h6 class="text-center mb-0">IUT Nancy-Charlemagne - Département Informatique - 2019/2020</h6>
    </div>
</div>
<br>