<h1 class="text-center"><u>A propos de MyWishList :</u></h1></br>

<h2 class="text-center">MyWishList.app</h2>
<p class="text-justify">
    MyWishList est une application en ligne pour créer, partager et gérer des listes de cadeaux.
    L'application permet à un utilisateur de créer une liste de souhaits à l'occasion d'un événement
    particulier (anniversaire, fin d'année, mariage, retraite …) et lui permet de diffuser cette liste de
    souhaits à un ensemble de personnes concernées. Ces personnes peuvent alors consulter cette liste
    et s'engager à offrir 1 élément de la liste. Cet élément est alors marqué comme réservé dans cette
    liste.
</p>
</br>

<div class="card bottom">
    <h1 class="card-title text-center mb-0"><u>Groupe :</u></h1>
    <div class="card-body">
        <h5 class="text-center">Julien Noël - <a href="https://github.com/juliennoel9">GitHub</a></h5>
        <h5 class="text-center">Louis Demanege - <a href="https://github.com/Nekzuris">GitHub</a></h5>
        <h5 class="text-center">Loïck Nosal - <a href="https://github.com/LoickNosal">GitHub</a></h5>
        <h5 class="text-center">Paul Gsell - <a href="https://github.com/poluxtobee">GitHub</a></h5>
        <h6 class="text-center mb-0">IUT Nancy-Charlemagne - Département Informatique - 2019/2020</h6>
    </div>
</div>
