<?php if (isset($_SESSION['login'])) : ?>
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mon compte</h5>
            </div>
            <form method="POST" action="<?= $router->pathFor('editAccount') ?>">
                <div class="modal-body">
                    <?php if (isset($_SESSION['redirect']['msg'])) {
                        echo $_SESSION['redirect']['msg'];
                        unset($_SESSION['redirect']['msg']);
                    } ?>
                    <div class="form-group">
                        <label for="prenom">Prénom</label>
                        <input required type="text" name="prenom" class="form-control" placeholder="Prénom" id="prenom" value="<?= $account->prenom ?>">
                    </div>
                    <div class="form-group">
                        <label for="nom">Nom</label>
                        <input required type="text" name="nom" class="form-control" placeholder="Nom" id="nom" value="<?= $account->nom ?>">
                    </div>
                    <div class="form-group">
                        <label for="username">Nom d'utilisateur</label>
                        <input disabled type="text" name="username" class="form-control" placeholder="Nom d'utilisateur" id="username" value="<?= $account->username ?>">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input required type="email" name="email" class="form-control" placeholder="Email" id="email" value="<?= $account->email ?>">
                    </div>

                    <div class="form-group">
                        <!-- Trigger modal password -->
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalPassword">Changer mot de passe</button>
                    </div>

                    <div class="form-group">
                        <!-- Trigger modal suppression compte -->
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalDeleteAccount">Supprimer mon compte</button>
                    </div>
                    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary" href="<?= $router->pathFor('home')?>" role="button">Retour</a>
                    <button type="submit" class="btn btn-success">Enregistrer les modifications</button>
                </div>
            </form>
        </div>

        <!-- Modal password -->
        <div class="modal fade" role="dialog" id="modalPassword">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Changer de mot de passe</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="<?= $router->pathFor('changePassword') ?>">
                            <div class="form-group">
                                <label for="oldPassword">Ancien mot de passe</label>
                                <div class="input-group">
                                    <input required type="password" name="oldPassword" class="form-control" placeholder="Ancien mot de passe" id="oldPassword">
                                    <div class="input-group-append">
                                        <button class="input-group-text" onclick="toggleVisibility('oldPassword')" type="button" style="outline: none" tabindex="-1"><i class="fas fa-eye"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="newPassword">Mot de passe</label>
                                <div class="input-group">
                                    <input required type="password" name="newPassword" class="form-control" placeholder="Nouveau mot de passe (minimum 8 caractères)" id="newPassword" minlength="8" maxlength="50">
                                    <div class="input-group-append">
                                        <button class="input-group-text" onclick="toggleVisibility('newPassword')" type="button" style="outline: none" tabindex="-1"><i class="fas fa-eye"></i></button>
                                    </div>
                                </div>
                                <meter value="0" min="-0.2" max="4" id="password-strength-meter" style="display: none"></meter>
                                <div class="font-weight-bold" id="password-security" style="display: none">Niveau de sécurité : </div>
                                <div class="invalid-feedback" id="passwordErr">Invalide</div>
                            </div>
                            <div class="form-group">
                                <label for="confirmPassWord">Confirmez votre mot de passe</label>
                                <div class="input-group">
                                    <input required type="password" name="confirmPassWord" class="form-control" placeholder="Confirmez votre mot de passe" id="confirmPassWord" minlength="8" maxlength="50">
                                    <div class="input-group-append">
                                        <button class="input-group-text" onclick="toggleVisibility('confirmPassWord')" type="button" style="outline: none" tabindex="-1"><i class="fas fa-eye"></i></button>
                                    </div>
                                </div>
                            </div>
                            <div id="confirmPassWordErr" class="alert alert-danger" style="display: none">Les deux mots de passe ne correspondent pas.</div>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                            <button type="submit" class="btn btn-warning">Changer le mot de passe</button>
                        </div>
                        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                    </form>
                </div>
            </div>
        </div>


        <!-- Modal suppression compte -->
        <div class="modal fade" role="dialog" id="modalDeleteAccount">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="POST" action="<?= $router->pathFor('deleteAccount') ?>">
                        <div class="modal-header">
                            <h5 class="modal-title">Supprimer mon compte</h5>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <div>Êtes-vous sûr de vouloir supprimer définitivement votre compte ?<br><br></div>
                            <div>Cela entraînera : la suppression des listes que vous avez créées, des items et images qu'elles contiennent, des participations (uniquement avant échéance de la liste) ainsi que la suppression de tous les messages.<br>De plus, cela annulera toutes les réservations que vous aurez effectué aupparavant.<br><br></div>
                            <div class="alert alert-danger">Attention, cette action est irréversible !</div>
                            <div class="form-group">
                                <label for="password">Mot de passe</label>
                                <div class="input-group">
                                    <input required type="password" name="password" class="form-control" placeholder="Mot de passe" id="password">
                                    <div class="input-group-append">
                                        <button class="input-group-text" onclick="toggleVisibility('password')" type="button" style="outline: none" tabindex="-1"><i class="fas fa-eye"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                                <button type="submit" class="btn btn-danger">Supprimer définitivement mon compte</button>
                                <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                                <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                        </div>
                    </form>
                </div>
            </div>
        </div>

<?php else: ?>
    <h1>Il faut être connecté pour accéder à cette page.</h1>
<?php endif; ?>

<script src="/public/js/zxcvbn.js"></script>
<script>
    let timer5, timer6;
    const finishTyping = 1000;
    let password = document.getElementById('newPassword');
    let passwordErr = document.getElementById('passwordErr');
    let confirm = document.getElementById('confirmPassWord');
    let confirmErr = document.getElementById('confirmPassWordErr');
    let meter = document.getElementById('password-strength-meter');
    let security = document.getElementById('password-security');
    const strength = {
        0: {text : 'Très faible', color : 'darkred'},
        1: {text : 'Faible', color : 'orangered'},
        2: {text : 'Moyen', color : 'orange'},
        3: {text : 'Fort', color : 'yellowgreen'},
        4: {text : 'Très fort', color : 'limegreen'}
    };
    password.addEventListener('input', function() {
        clearTimeout(timer5);
        meter.style.display = this.value ? "inline" : "none";
        meter.value = zxcvbn(this.value).score;
        security.style.display = this.value ? 'block' : 'none';
        security.innerText = 'Niveau de sécurité : ' + strength[meter.value].text;
        security.style.color = strength[meter.value].color;
        password.className = 'form-control';
        password.setCustomValidity('');
        confirm.className = 'form-control';
        confirm.setCustomValidity('');
        confirmErr.style.display = "none";
        timer5 = setTimeout(checkPassword, finishTyping);
        timer5 = setTimeout(checkConfirm, finishTyping);
    });

    confirm.addEventListener('input', function() {
        clearTimeout(timer6);
        password.className = 'form-control';
        password.setCustomValidity('');
        confirm.className = 'form-control';
        confirm.setCustomValidity('');
        confirmErr.style.display = "none";
        timer6 = setTimeout(checkConfirm, finishTyping);
    });

    function checkPassword() {
        if (password.value.length < 8) {
            password.className = 'form-control is-invalid';
            passwordErr.innerText = 'Veuillez utiliser au moins 8 caractères.';
            password.setCustomValidity(passwordErr.innerText);
        }
    }

    function checkConfirm() {
        if (password.value !== confirm.value && confirm.value) {
            password.className = 'form-control is-invalid';
            password.setCustomValidity('');
            passwordErr.innerText = '';
            confirm.className = 'form-control is-invalid';
            confirm.setCustomValidity('Les deux mots de passe ne correspondent pas.');
            confirmErr.style.display = "block";
        }
    }

    function toggleVisibility($input) {
        $input = document.getElementById($input);
        if ($input.type === 'password') {
            $input.type = 'text';
            $input.nextElementSibling.firstElementChild.firstElementChild.className = 'fas fa-eye-slash';
        } else {
            $input.type = 'password';
            $input.nextElementSibling.firstElementChild.firstElementChild.className = 'fas fa-eye';
        }
    }
</script>
