<?php if (isset($_SESSION['login'])) : ?>
    <h1>Mes listes</h1>
    <div class="body">

        <?php if (sizeof($lists) > 0) : ?>
            <?php foreach ($lists as $list) : ?>
                <div class="card mt-4 bg-light">
                    <div class="card-body text-center pb-1">
                        <h1 class="card-title"><?= $list->titre ?></h1>
                    <?php if (!$list->public) : ?>
                        <h4 class="float-left">&#x1F512</h4>
                    <?php endif; ?>
                        <p class="card-text lead"><?= $list->description ?></p>
                        <?php if (strtotime($list->expiration) > strtotime("-1 days")) : ?>
                            <p class="text-success">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
                        <?php else: ?>
                            <p class="text-danger">Expirée depuis le : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
                        <?php endif; ?>
                        <a href='<?= $router->pathFor('list', ['token' => $list->token]) ?>' class="stretched-link"></a>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <p>Vous ne disposez pour le moment d'aucune liste. Vous pouvez en créer une dès maintenant en cliquant sur le bouton ci-dessous.</p>
        <?php endif; ?>
    </div>
    <br>
    <div class="modal-footer">
        <a class="btn btn-success" href="<?= $router->pathFor('newList')?>" role="button">Créer une nouvelle liste</a>
    </div>
<?php else: ?>
    <h1>Il faut être connecté pour accéder à cette page.</h1>
<?php endif; ?>