<form method="POST" id="account">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Mon compte</h5>
        </div>
        <div class="modal-body">
            <?php if (isset($msg)) : ?>
                <?= $msg ?>
            <?php endif; ?>
            <?php if (pathinfo($_SERVER['HTTP_REFERER'])['filename']=='inscription') : ?>
                <div class="alert alert-success">Compte créé avec succès !</div>
            <?php endif; ?>
            <?php if (pathinfo($_SERVER['HTTP_REFERER'])['filename']=='moncompte') : ?>
                <div class="alert alert-success">Modifications enregistrées.</div>
            <?php endif; ?>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input required type="text" name="prenom" class="form-control" placeholder="Prénom" id="prenom" value="<?= $account->prenom ?>">
            </div>
            <div class="form-group">
                <label for="nom">Prénom</label>
                <input required type="text" name="nom" class="form-control" placeholder="Nom" id="nom" value="<?= $account->nom ?>">
            </div>
            <div class="form-group">
                <label for="username">Nom d'utilisateur</label>
                <input disabled type="text" name="username" class="form-control" placeholder="Nom d'utilisateur" id="username" value="<?= $account->username ?>">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input required type="email" name="email" class="form-control" placeholder="Email" id="email" value="<?= $account->email ?>">
            </div>

            <!-- Trigger modal reservation -->
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalPassword">Changer mot de passe</button>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary">Annuler</button>
            <button type="submit" name="submit" value="edit" class="btn btn-warning">Enregistrer les modifications</button>
        </div>
    </div>

    <!-- Modal reservation -->
    <div class="modal fade" role="dialog" id="modalPassword">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Changer de mot de passe</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="oldPassword">Ancien mot de passe</label>
                        <input minlength="8" type="password" name="oldPassword" class="form-control" placeholder="Ancien mot de passe" id="oldPassword">
                    </div>
                    <div class="form-group">
                        <label for="newPassword">Mot de passe</label>
                        <input  minlength="8" type="password" name="newPassword" class="form-control" placeholder="Nouveau mot de passe" id="newPassword">
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                    <button type="submit" name="submit" value="editPassword" class="btn btn-warning">Changer le mot de passe</button>
                </div>
            </div>
        </div>
    </div>
</form>