<?php if (isset($_SESSION['login']) and $list->user_id==$account->id and strtotime($list->expiration) > strtotime("-1 days")) : ?>
    <form method="POST" enctype="multipart/form-data">
        <h1>Modifiez votre item</h1><br>
        <div class="form-group">
            <label for="nom">Donnez un nouveau nom à l'item</label>
            <input required type="text" placeholder="Nom de l'item" name="nom" class="form-control" id="titre" value="<?= htmlspecialchars($item->nom) ?>">
        </div>
        <div class="form-group">
            <label for="description">Modifiez la description</label>
            <input required type="text" value="<?= htmlspecialchars($item->descr) ?>" name="description" class="form-control" id="description">
        </div>
        <div class="form-group">
            <label for="tarif">Modifiez le prix</label>
            <input required type="number" step="0.01" min="0" max="99999999.99" value="<?= $item->tarif ?>" name="tarif" class="form-control" id="tarif">
        </div>
        <div class="form-group">
            <div>
                <label for="img">Modifiez l'image de l'item</label>
                <span
                        data-trigger="hover"
                        data-toggle="popover"
                        title="Informations pour l'image"
                        data-content="Formats acceptés : PNG, JPG, JPEG de taille inférieure ou égale à 10Mo. Si un autre format est sélectionné ou que l'image est trop volumineuse, aucune image ne sera importée.">
                &#8505;
            </span>
            </div>
            <input type="file" name="img" class="form-control-file" id="img">
            <label class="form-check-label" for="delete">Supprimer l'image actuelle ?</label>
            <input type="checkbox" class="form-check-inline" id="delete" name="delete">
        </div>
        <div class="form-group">
            <label for="url">Modifier l'URL externe de l'item</label>
            <input type="url" placeholder="URL externe" value="<?= $item->url ?>" name="url" class="form-control" id="url">
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" href="<?= $router->pathFor('item', ['token' => $list->token, 'id' => $item->id])?>" role="button">Annuler</a>

            <!-- Trigger modal delete -->
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalDelete">Supprimer l'item</button>

            <button type="submit" name="submit" class="btn btn-primary" value="edit">Modifier l'item</button>
        </div>

        <!-- Modal delete -->
        <div class="modal fade" role="dialog" id="modalDelete">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Supprimer l'item</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div>Êtes-vous sûr de vouloir supprimer l'item ?<br><br></div>
                        <div>Cela entraînera la suppression de l'item au sein de la liste.<br><br></div>
                        <div class="alert alert-danger">Attention, cette action est irréversible !</div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                        <button type="submit" name="submit" value="delete" class="btn btn-danger">Supprimer l'item</button>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    </form>
<?php else: ?>
    <h1>Connectez-vous pour pouvoir modifier cet item s'il vous appartient et si la date d'expiration de la liste à laquelle il appartient n'est pas déjà passée.</h1>
<?php endif; ?>


<script>
    $(function () {
        $('[data-toggle="popover"]').popover()
    })
</script>