<h1>Modifiez votre item</h1><br>
<form method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label for="nom">Donnez un nouveau nom à l'item</label>
        <input required type="text" placeholder="Nom de l'item" name="nom" class="form-control" id="titre" value="<?= $item->nom ?>">
    </div>
    <div class="form-group">
        <label for="description">Modifiez la description</label>
        <input required type="text" value="<?= $item->descr ?>" name="description" class="form-control" id="description">
    </div>
    <div class="form-group">
        <div>
            <label for="img">Modifiez l'image de l'item</label>
            <span
                    data-trigger="hover"
                    class="rounded-circle btn-sm btn-info text-white"
                    data-toggle="popover"
                    title="Informations pour l'image"
                    data-content="Formats acceptés : PNG, JPG, JPEG de taille inférieure ou égale à 10Mo. Si un autre format est sélectionné ou que l'image est trop volumineuse, aucune image ne sera importée.">
                i
            </span>
        </div>
        <input type="file" name="img" class="form-control-file" id="img">
        <label class="form-check-label" for="delete">Supprimer l'image actuelle ?</label>
        <input type="checkbox" class="form-check-inline" id="delete" name="delete">
    </div>
    <div class="form-group">
        <label for="url">Modifier l'URL externe de l'item</label>
        <input type="url" placeholder="URL externe" value="<?= $item->url ?>" name="url" class="form-control" id="url">
    </div>
    <div class="modal-footer">
        <a href="<?= $router->pathFor('item', ['token' => $list->token, 'id' => $item->id])?>"><button type="button" class="btn btn-secondary">Annuler</button></a>

        <button type="submit" name="submit" class="btn btn-danger" value="delete">Supprimer Item</button>

        <button type="submit" name="submit" class="btn btn-primary" value="edit">Modifier l'item</button>
    </div>
</form>

<script src="/public/js/jquery.slim.min.js"></script>
<script src="/public/js/popper.min.js"></script>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover()
    })
</script>