<?php if (isset($_SESSION['login']) and $list->user_id==$account->id) : ?>
    <form method="POST">
        <h1>Modifiez votre liste</h1><br>
        <div class="form-group">
            <label for="titre">Donnez un nouveau titre à la liste</label>
            <input required type="text" placeholder="Titre" name="titre" class="form-control" id="titre" value="<?= htmlspecialchars($list->titre) ?>" <?= strtotime($list->expiration) > strtotime("-1 days") ? '' : 'disabled' ?>>
        </div>
        <div class="form-group">
            <label for="expiration">Indiquez une nouvelle date d'expiration</label>
            <input required type="date" value="<?= date("Y-m-d", strtotime($list->expiration)) ?>" name="expiration" class="form-control" id="expiration" <?= strtotime($list->expiration) > strtotime("-1 days") ? '' : 'disabled' ?>>
            <div class="invalid-feedback" id="expirationErr">Invalide</div>
        </div>
        <div class="form-group">
            <label for="description">Changez une description à la liste</label>
            <textarea required class="form-control" name="description" id="description" rows="3" <?= strtotime($list->expiration) > strtotime("-1 days") ? '' : 'disabled' ?>><?= htmlspecialchars($list->description) ?></textarea>
        </div>
        <div class="form-check">
            <input type="checkbox" <?= $list->public === 1 ? 'checked=\"checked\"' : ''?> class="form-check-input" id="public" name="public">
            <label class="form-check-label" for="public">Publique</label>
        </div>
        <div class="modal-footer">
            <a class="btn btn-secondary" href="<?= $router->pathFor('list', ['token' => $list->token])?>" role="button">Annuler</a>
            <?php
                $notReserved = true;
                foreach ($items as $item) :
                    if ($item->account_id_reserv != null) :
                        $notReserved = false;
                        break;
                    endif;
                endforeach;
            ?>
            <?php
            $cagnottes = 0;
            foreach ($list->items() as $item) {
                $cagnottes += $item->cagnottes()->count();
            }
            ?>
            <?php if (isset($_SESSION['login']) and $list->user_id==$account->id and ( strtotime($list->expiration) < strtotime("-1 days") or $notReserved ) and $cagnottes == 0) : ?>
                <!-- Trigger modal delete -->
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modalDelete">Supprimer la liste</button>
            <?php endif; ?>

            <button type="submit" name="submit" class="btn btn-primary" value="edit">Modifier la liste</button>
        </div>

        <!-- Modal delete -->
        <div class="modal fade" role="dialog" id="modalDelete">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Supprimer la liste</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div>Êtes-vous sûr de vouloir supprimer la liste ?<br><br></div>
                        <div>Cela entraînera la suppression la liste ainsi que de tous les items au sein de la liste.<br><br></div>
                        <div class="alert alert-danger">Attention, cette action est irréversible !</div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                        <button type="submit" name="submit" value="delete" class="btn btn-danger">Supprimer la liste</button>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    </form>
<?php else: ?>
<h1>Connectez-vous pour pouvoir modifier cette liste si elle vous appartient.</h1>
<?php endif; ?>

<script>
    /* pour lancer le check apres 1 sec d'inactivité dans l'input */
    let timer;
    const finishTyping = 1000;
    let date = document.getElementById('expiration');
    let dateErr = document.getElementById('expirationErr');

    date.addEventListener('input', function() {
        clearTimeout(timer);
        date.className = 'form-control';
        date.setCustomValidity('');
        timer = setTimeout(checkDate, finishTyping);
    });

    function checkDate() {
        fetch('<?= $rootUri ?>/live_check?date=' + encodeURIComponent(date.value))
            .then(response => {
                return response.json();
            })
            .then(data => {
                if (!data.valid) {
                    date.className = 'form-control is-invalid';
                    dateErr.innerText = data.error;
                    date.setCustomValidity(data.error);
                }
            })
    }
</script>
