<section class="jumbotron text-center mt-4 pt-3 pb-2">
    <div class="container">
        <h1 class="jumbotron-heading"><?= htmlspecialchars($list->titre) ?></h1>
        <?php if (!$list->public) : ?>
            <h4 class="float-left">&#x1F512</h4>
        <?php endif; ?>
        <p class="lead text-muted"><?= htmlspecialchars($list->description) ?></p>
        <p class="lead text-muted">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
    </div>
</section>

<div class="container mt-4">
    <a class="btn btn-secondary" href="<?= $router->pathFor('list', ['token' => $list->token]) ?>" role="button">Retour à la liste</a><br><br>
    <?php if($item->account_id_reserv != null) : ?>
        <?php if (isset($_SESSION['login']) and $list->user_id==$account->id) : ?>
            <?php if (strtotime($list->expiration) > strtotime("-1 days")) : ?>
                <div class="alert alert-success">Produit réservé</div>
            <?php else: ?>
                <div class="alert alert-success">Produit réservé par : <?= htmlspecialchars($reserveName) ?> <br> Message : <?= htmlspecialchars($item->messageReservation) ?></div>
            <?php endif; ?>
        <?php else: ?>
            <div class="alert alert-success">Produit réservé par : <?= htmlspecialchars($reserveName) ?></div>
        <?php endif; ?>
    <?php endif; ?>

    <?php
        $fileName = 'noimage.png';
        if (file_exists('./public/images/'.$item->img)) {
            $fileName = $item->img;
        }
    ?>

    <!-- Trigger modal image -->
    <a data-toggle="modal" data-target="#modalIMG">
        <img class="rounded float-left img-thumbnail" width=40% src="/public/images/<?= $fileName ?>">
    </a>

    <!-- Modal image -->
    <div class="modal fade" id="modalIMG" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalIMG"><?= htmlspecialchars($item->nom) ?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <img class="card-img" src="/public/images/<?= $fileName ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="text-center">
        <h5 class="text-uppercase font-weight-bold m-auto text-center"><strong><?= htmlspecialchars($item->nom) ?></strong></h5>
        <p><?= htmlspecialchars($item->descr) ?></p>
        <p><strong><?= $item->tarif ?> €</strong></p>
        <?php if ($item->url != '') : ?>
            <p>Informations supplémentaires :<br><a href="<?= $item->url ?>"><?= $item->url ?></a></p>
        <?php endif ?>
    </div>
</div>

<?php if ($item->account_id_reserv == '') : ?>
    <div class="modal-footer">
        <?php if (isset($_SESSION['login']) and $list->user_id==$account->id and  strtotime($list->expiration) > strtotime("-1 days")) : ?>
            <a class="btn btn-secondary" href="<?= $router->pathFor('editItem', ['token' => $list->token, 'id' => $item->id]) ?>" role="button">Modifier Item</a>
        <?php endif; ?>

        <?php if (isset($_SESSION['login'])) : ?>
            <?php if ($account->id != $list->user_id) : ?>
                <form method="post" action="<?= $router->pathFor('reserveItem', ['token' => $list->token, 'id' => $item->id]) ?>">
                    <!-- Trigger modal reservation -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalReservation">Réserver l'item</button>

                    <!-- Modal reservation -->
                    <div class="modal fade" role="dialog" id="modalReservation">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Réserver l'item</h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="nom">Nom</label>
                                        <?php if (isset($_SESSION['login'])) : ?>
                                            <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" value="<?= htmlspecialchars(unserialize($_SESSION['login'])['prenom']) ?> <?= htmlspecialchars(unserialize($_SESSION['login'])['nom']) ?>" id="nom">
                                        <?php else : ?>
                                            <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" id="nom">
                                        <?php endif; ?>
                                    </div>
                                    <div class="form-group">
                                        <label for="message">Message</label>
                                        <input required name="message" class="form-control" placeholder="Votre message" id="message">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                                    <button type="submit" class="btn btn-success">Réserver</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                </form>
            <?php endif; ?>
        <?php else: ?>
            <div class="text-danger">Il faut être inscrit et connecté pour réserver un item.</div>
        <?php endif; ?>

    </div>
<?php endif ?>