<section class="jumbotron text-center mt-4">
    <div class="container">
        <h1 class="jumbotron-heading"><?= $list->titre ?></h1>
        <p class="lead text-muted"><?= $list->description ?></p>
        <p class="lead text-muted">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
    </div>
</section>

<div class="container mt-4">
    <?php
        $fileName = 'noimage.png';
        if (file_exists('./public/images/'.$item->img)){
            $fileName = $item->img;
        }
    ?>

    <!-- Trigger modal -->
    <a data-toggle="modal" data-target="#modalIMG">
        <img class="rounded float-left img-thumbnail" width=40% src="/public/images/<?= $fileName ?>">
    </a>

    <!-- Modal -->
    <div class="modal fade" id="modalIMG" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalIMG"><?= $item->nom ?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <img class="card-img" src="/public/images/<?= $fileName ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="text-center">
        <h5 class="text-uppercase font-weight-bold m-auto text-center"><strong><?= $item->nom ?></strong></h5>
        <p><?= $item->descr ?></p>
        <p><strong><?= $item->tarif ?> €</strong></p>
        <?php if ($item->url != '') : ?>
            <p>Informations supplémentaires :<br><a href="<?= $item->url ?>"><?= $item->url ?></a></p>
        <?php endif ?>
    </div>
</div>

<?php if ($item->reserve == '') : ?>
    <div class="modal-footer">
        <button onclick="document.location='<?= $router->pathFor('editItem', ['token' => $list->token, 'id' => $item->id]) ?>';" type="button" class="btn btn-secondary">Modifier Item</button>
        <form method="post" action="<?= $router->pathFor('deleteItem', ['token' => $list->token, 'id' => $item->id]) ?>">
            <button type="submit" class="btn btn-danger">Supprimer Item</button>
        </form>
    </div>
<?php endif ?>