<section class="jumbotron text-center mt-4 pt-3 pb-2">
<div class="container">
        <?php if (!$list->public) : ?>
            <p class="float-left">&#x1F512</p>
        <?php endif; ?>
        <h1 class="jumbotron-heading"><?= $list->titre ?></h1>
        <p class="lead text-muted"><?= $list->description ?></p>
        <p class="lead text-muted">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
    </div>
</section>

<div class="container mt-4">
    <?php if($item->nomReservation != null) : ?>
        <?php if (isset($_SESSION['login']) and $list->user_id==$account->id) : ?>
            <?php if (strtotime($list->expiration) >= time()) : ?>
                <div class="alert alert-success">Produit réservé</div>
            <?php else: ?>
                <div class="alert alert-success">Produit réservé par : <?= $item->nomReservation ?> <br> Message : <?= $item->messageReservation ?></div>
            <?php endif; ?>
        <?php else: ?>
            <div class="alert alert-success">Produit réservé par : <?= $item->nomReservation ?></div>
        <?php endif; ?>
    <?php endif; ?>

    <?php
        $fileName = 'noimage.png';
        if (file_exists('./public/images/'.$item->img)){
            $fileName = $item->img;
        }
    ?>

    <!-- Trigger modal image -->
    <a data-toggle="modal" data-target="#modalIMG">
        <img class="rounded float-left img-thumbnail" width=40% src="./public/images/<?= $fileName ?>">
    </a>

    <!-- Modal image -->
    <div class="modal fade" id="modalIMG" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalIMG"><?= $item->nom ?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <img class="card-img" src="./public/images/<?= $fileName ?>">
                </div>
            </div>
        </div>
    </div>

    <div class="text-center">
        <h5 class="text-uppercase font-weight-bold m-auto text-center"><strong><?= $item->nom ?></strong></h5>
        <p><?= $item->descr ?></p>
        <p><strong><?= $item->tarif ?> €</strong></p>
        <?php if ($item->url != '') : ?>
            <p>Informations supplémentaires :<br><a href="<?= $item->url ?>"><?= $item->url ?></a></p>
        <?php endif ?>
    </div>
</div>

<?php if ($item->nomReservation == '') : ?>
    <div class="modal-footer">
        <?php if (isset($_SESSION['login']) and $list->user_id==$account->id and  strtotime($list->expiration) >= time()) : ?>
            <button onclick="document.location='<?= $router->pathFor('editItem', ['token' => $list->token, 'id' => $item->id]) ?>';" type="button" class="btn btn-secondary">Modifier Item</button>
        <?php endif; ?>

        <?php if (isset($_SESSION['login'])) : ?>
            <?php if ($account->id != $list->user_id) : ?>
                <form method="post" action="<?= $router->pathFor('reserveItem', ['token' => $list->token, 'id' => $item->id]) ?>">
                    <!-- Trigger modal reservation -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalReservation">Réserver l'item</button>

                    <!-- Modal reservation -->
                    <div class="modal fade" role="dialog" id="modalReservation">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Réserver l'item</h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="nom">Nom</label>
                                        <?php if (isset($_SESSION['login'])) : ?>
                                            <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" value="<?= unserialize($_SESSION['login'])['prenom'] ?> <?= unserialize($_SESSION['login'])['nom'] ?>" id="nom">
                                        <?php else : ?>
                                            <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" id="nom">
                                        <?php endif; ?>
                                    </div>
                                    <div class="form-group">
                                        <label for="message">Message</label>
                                        <input required name="message" class="form-control" placeholder="Votre message" id="message">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                                    <button type="submit" class="btn btn-success">Réserver</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <?php endif; ?>
        <?php else: ?>
            <form method="post" action="<?= $router->pathFor('reserveItem', ['token' => $list->token, 'id' => $item->id]) ?>">
                <!-- Trigger modal reservation -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalReservation">Réserver l'item</button>

                <!-- Modal reservation -->
                <div class="modal fade" role="dialog" id="modalReservation">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Réserver l'item</h5>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="nom">Nom</label>
                                    <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" id="nom">
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <input required name="message" class="form-control" placeholder="Votre message" id="message">
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                                <button type="submit" class="btn btn-success">Réserver</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        <?php endif; ?>

    </div>
<?php endif ?>