<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="<?= $rootUri ?>/public/images/icon.png" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/style.css">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0/css/all.css"/>
    <title><?=$title?></title>
</head>
<body>
    <script src="<?= $rootUri ?>/public/js/jquery.slim.min.js"></script>
    <script src="<?= $rootUri ?>/public/js/popper.min.js"></script>
    <script src="<?= $rootUri ?>/public/js/bootstrap.min.js"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container">
            <a class="navbar-brand" href="<?= $router->pathFor('home') ?>">MyWishList</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $router->pathFor('home') ?>">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $router->pathFor('publicLists') ?>">Listes publiques</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $router->pathFor('creators') ?>">Créateurs</a>
                    </li>
                    <?php if (isset($_SESSION['login'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $router->pathFor('accountLists') ?>">Mes listes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $router->pathFor('newList') ?>">Créer liste</a>
                        </li>
                    <?php endif; ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $router->pathFor('about') ?>">À propos</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <?php if (isset($_SESSION['login'])) : ?>
                        <li class="nav-item">
                            <a class="nav-link logout" href="<?= $router->pathFor('logout') ?>">Déconnexion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $router->pathFor('account') ?>">Mon compte</a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $router->pathFor('register') ?>">Inscription</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $router->pathFor('login') ?>">Connexion</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-3">
        <?= $content ?>
    </div>

</body>
</html>