<h1>Liste n°<?=$list->num?></h1>
<div class="body mt-5">
    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">ID Liste</th>
            <th scope="col">Nom</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
            <th scope="col">URL</th>
            <th scope="col">Tarif</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($items as $item) : ?>
            <tr onclick="document.location='<?= $router->pathFor('item', ['num' => $list->num, 'id' => $item->id]) ?>';">
                <th scope="row"><?= $item->id ?></th>
                <td><?= $item->liste_id ?></td>
                <td><?= $item->nom ?></td>
                <td><?= $item->descr ?></td>
                <td class="text-center"><img src="/public/images/<?= $item->img ?>"></td>
                <td><?= $item->ur ?></td>
                <td><?= $item->tarif ?>€</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if (isset($_GET['token']) and $_GET['token'] === $list->token) : ?>
    <div class="modal-footer">
        <button onclick="document.location='<?= $router->pathFor('editList', ['token' => $list->token]) ?>';" type="button" class="btn btn-secondary">Modifier</button>
    </div>
    <?php endif ?>
</div>