<h1>Liste n°<?=$list->num?></h1>
<div class="body mt-5">
    <section class="jumbotron text-center mt-4 pt-3 pb-2">
        <div class="container">
            <?php if (!$list->public) : ?>
                <p class="float-left">&#x1F512</p>
            <?php endif; ?>
            <h1 class="jumbotron-heading"><?= $list->titre ?></h1>
            <p class="lead text-muted"><?= $list->description ?></p>
            <?php if (strtotime($list->expiration) > time()) : ?>
                <p class="text-success">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
            <?php else: ?>
                <p class="text-danger">Expirée depuis le : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
            <?php endif; ?>
        </div>
    </section>

    <?php if (sizeof($items) != 0) : ?>
        <table class="table table-bordered table-hover table-dark">
            <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Image</th>
                <th scope="col">Réservation</th>
            </tr>
            </thead>

            <tbody>
            <?php foreach ($items as $item) :
                    $fileName = 'noimage.png';
                    if (file_exists('./public/images/' . $item->img)) {
                        $fileName = $item->img;
                    }
                ?>
                <div class="card mt-4 bg-light">
                    <div class="card-body text-center pb-1">
                        <img class="float-left w-50" src="/public/images/<?= $fileName ?>">
                        <h1 class="card-title"><?= $item->nom ?></h1>
                        <p class="card-text lead"><?= $item->description ?></p>
                        <?php if (strtotime($list->nomReservation)) : ?>
                            <p><?= $list->nomReservation ?></p>
                        <?php else: ?>
                            <p>Non réservé</p>
                        <?php endif; ?>
                        <a href='<?= $router->pathFor('item', ['token' => $list->token, 'id' => $item->id]) ?>' class="stretched-link"></a>
                    </div>
                </div>
            <?php endforeach; ?>

            <?php foreach ($items as $item) : ?>
                <tr onclick="document.location='<?= $router->pathFor('item', ['token' => $list->token, 'id' => $item->id]) ?>';">
                    <th scope="row"><?= $item->nom ?></th>
                    <?php
                        $fileName = 'noimage.png';
                        if (file_exists('./public/images/' . $item->img)) {
                            $fileName = $item->img;
                        }
                    ?>
                    <td class="text-center"><img class="img-fluid" src="/public/images/<?= $fileName ?>"></td>
                    <td><?= $item->nomReservation == null ? 'Non réservé' : 'Réservé'?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <?php if (isset($_SESSION['login']) and $list->user_id==$account->id) : ?>
            <p>Vous ne disposez pour le moment d'aucun produit dans votre liste. Vous pouvez en ajouter dès maintenant en cliquant sur le bouton ci-dessous.</p>
        <?php else: ?>
            <p>Cette liste ne contient aucun produit.</p>
        <?php endif; ?>
    <?php endif; ?>

    <?php if($messages->count() > 0 ) : ?>
        <div class="jumbotron modal-body">
            <div class="modal-title"><h3>Messages des participants</h3></div>
            <div class="modal-body">
                <?php foreach ($messages as $message) : ?>
                    <h5><?= $message->nomMessage ?> le <?= date("d/m/Y", strtotime($message->date)) ?> à <?= date("H:i", strtotime($message->date)) ?></h5>
                    <p><?= $message->message ?></p>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>

    <div class="modal-footer">
        <!-- Trigger modal URL -->
        <button href="<?= pathinfo($_SERVER['HTTP_HOST'])['filename'].pathinfo($_SERVER['REQUEST_URI'])['dirname'].'/'.pathinfo($_SERVER['REQUEST_URI'])['filename']; ?>" type="button" class="btn btn-primary" id="url" data-toggle="modal" data-target="#modalURL">Partager URL</button>

        <!-- Modal URL -->
        <div class="modal fade" role="dialog" id="modalURL">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Partager l'URL</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <div class="text-center js-text" id="text"><?= pathinfo($_SERVER['HTTP_HOST'])['filename'].pathinfo($_SERVER['REQUEST_URI'])['dirname'].'/'.pathinfo($_SERVER['REQUEST_URI'])['filename']; ?></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                        <button id="copy" type="button" class="btn btn-success js-copyButton">Copier l'URL</button>
                    </div>
                </div>
            </div>
        </div>

        <?php if (isset($_SESSION['login']) and $list->user_id==$account->id) : ?>
            <?php if (strtotime($list->expiration) >= time()) : ?>
                <button onclick="document.location='<?= $router->pathFor('newItem', ['token' => $list->token]) ?>';" type="button" class="btn btn-success">Ajouter Item</button>
            <?php endif; ?>
            <button onclick="document.location='<?= $router->pathFor('editList', ['token' => $list->token]) ?>';" type="button" class="btn btn-secondary">Modifier Liste</button>
        <?php endif; ?>

        <?php if (strtotime($list->expiration) >= time()) : ?>
            <?php if (isset($_SESSION['login']) ) : ?>
                <?php if ($list->user_id != $account->id) : ?>
                    <form method="post" action="<?= $router->pathFor('newListMessage', ['token' => $list->token]) ?>">
                        <!-- Trigger modal message -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalMessage">Ajouter un message</button>

                        <!-- Modal message -->
                        <div class="modal fade" role="dialog" id="modalMessage">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Ajouter un message à la liste n°<?= $list->num ?></h5>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="nom">Nom</label>
                                            <?php if (isset($_SESSION['login'])) : ?>
                                                <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" value="<?= unserialize($_SESSION['login'])['prenom'] ?> <?= unserialize($_SESSION['login'])['nom'] ?>" id="nom">
                                            <?php else : ?>
                                                <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" id="nom">
                                            <?php endif; ?>
                                        </div>
                                        <div class="form-group">
                                            <label for="message">Message</label>
                                            <input required name="message" class="form-control" placeholder="Votre message" id="message">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                                        <button type="submit" class="btn btn-success">Ajouter Message</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                <?php endif; ?>
            <?php else: ?>
                <form method="post" action="<?= $router->pathFor('newListMessage', ['token' => $list->token]) ?>">
                    <!-- Trigger modal message -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalMessage">Ajouter un message</button>

                    <!-- Modal message -->
                    <div class="modal fade" role="dialog" id="modalMessage">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Ajouter un message à la liste n°<?= $list->num ?></h5>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="nom">Nom</label>
                                        <?php if (isset($_SESSION['login'])) : ?>
                                            <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" value="<?= unserialize($_SESSION['login'])['prenom'] ?> <?= unserialize($_SESSION['login'])['nom'] ?>" id="nom">
                                        <?php else : ?>
                                            <input required type="text" name="nom" class="form-control" placeholder="Prénom Nom" id="nom">
                                        <?php endif; ?>
                                    </div>
                                    <div class="form-group">
                                        <label for="message">Message</label>
                                        <input required name="message" class="form-control" placeholder="Votre message" id="message">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Annuler</button>
                                    <button type="submit" class="btn btn-success">Ajouter Message</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>

<script>
    const button = document.querySelector('.js-copyButton');

    button.addEventListener('click', function () {
        const text = document.querySelector('.js-text');
        const range = document.createRange();

        range.selectNode(text);
        window.getSelection().addRange(range);

        if (document.execCommand('copy')) {
            alert('URL copiée dans le presse-papier !');
        }

        window.getSelection().removeAllRanges();
    });
</script>