<div class="body mt-5">
    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">Numéro</th>
            <th scope="col">UserID</th>
            <th scope="col">Titre</th>
            <th scope="col">Description</th>
            <th scope="col">Expiration</th>
            <th scope="col">Token</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($listes as $liste) : ?>
            <tr onclick="document.location='<?= $router->pathFor('about') ?>';">
                <th scope="row"><?= $liste->no ?></th>
                <td><?= $liste->user_id ?></td>
                <td><?= $liste->titre ?></td>
                <td><?= $liste->description ?></td>
                <td><?= $liste->expiration ?></td>
                <td><?= $liste->token ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>