<h1>Liste n°<?=$list->num?></h1>
<div class="body mt-5">

    <section class="jumbotron text-center mt-4">
        <div class="container">
            <h1 class="jumbotron-heading"><?= $list->titre ?></h1>
            <p class="lead text-muted"><?= $list->description ?></p>
            <p class="lead text-muted">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
        </div>
    </section>






    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">ID Liste</th>
            <th scope="col">Nom</th>
            <th scope="col">Description</th>
            <th scope="col">Image</th>
            <th scope="col">URL</th>
            <th scope="col">Tarif</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($items as $item) : ?>
            <tr onclick="document.location='<?= $router->pathFor('item', ['num' => $list->num, 'id' => $item->id]) ?>';">
                <th scope="row"><?= $item->id ?></th>
                <td><?= $item->liste_id ?></td>
                <td><?= $item->nom ?></td>
                <td><?= $item->descr ?></td>
                <?php if (!is_null($item->img)) : ?>
                    <td class="text-center"><img src="/public/images/<?= $item->img ?>"></td>
                <?php else : ?>
                    <td class="text-center"></td>
                <?php endif ?>
                <?php if ($item->url=='') : ?>
                    <td></td>
                <?php else : ?>
                    <td><a href="<?= $item->url ?>">URL</a></td>
                <?php endif ?>
                <td><?= $item->tarif ?>€</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if (isset($_GET['token']) and $_GET['token'] === $list->token) : ?>
        <div class="modal-footer">
            <button onclick="document.location='<?= $router->pathFor('newItem', ['token' => $list->token]) ?>';" type="button" class="btn btn-secondary">Ajouter Item</button>
            <button onclick="document.location='<?= $router->pathFor('editList', ['token' => $list->token]) ?>';" type="button" class="btn btn-secondary">Modifier Liste</button>
        </div>
    <?php endif ?>
</div>