<?php if (!isset($_SESSION['login'])) : ?>
    <form method="post" action="<?= $router->pathFor('login') ?>">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Connexion</h3>
                    </div>
                    <div class="modal-body">
                        <?php if (isset($msg)) : ?>
                            <?= $msg ?>
                        <?php endif; ?>
                        <div class="form-group">
                            <label for="id">Email ou nom d'utilisateur</label>
                            <input required type="text" name="id" class="form-control" placeholder="Email ou nom d'utilisateur" id="id" <?= isset($id) ? 'value='.$id : 'autofocus'?>>
                            <div class="invalid-feedback" id="idErr">Invalide</div>
                        </div>
                        <div class="form-group">
                            <label for="password">Mot de passe</label>
                            <input required type="password" name="password" class="form-control" placeholder="Mot de passe" id="password">
                        </div>
                        <div class="form-group">Vous n'avez pas encore de compte ? <a href="<?= $router->pathFor('register') ?>">S'inscrire</a></div>
                    </div>
                    <div class="modal-footer">
                        <?php if(pathinfo($_SERVER['REQUEST_URI'])['filename']=='moncompte') : ?>
                            <button type="button" class="btn btn-secondary" onclick="document.location='<?= $router->pathFor('home') ?>'">Annuler</button>
                        <?php else: ?>
                            <button type="button" class="btn btn-secondary" onclick="document.location='<?= $_SERVER['HTTP_REFERER']?>'">Annuler</button>
                        <?php endif; ?>
                        <button type="submit" class="btn btn-success">Connexion</button>
                    </div>
                </div>
            </div>
    </form>
<?php else: ?>
    <h1>Vous êtes déjà connecté. Cette page n'est pas disponible.</h1>
    <h4>Si vous voulez vous connecter avec un autre compte, déconnectez vous auparavant.</h4>
<?php endif; ?>

<script>
    /* pour lancer le check apres 1 sec d'inactivité dans l'input */
    let timer;
    const finishTyping = 1000;
    let login = document.getElementById('id');
    let loginErr = document.getElementById('idErr');

    login.addEventListener('input', function(e) {
        clearTimeout(timer);
        login.className = 'form-control';
        login.setCustomValidity('');
        timer = setTimeout(checkLogin, finishTyping);
    });

    function checkLogin() {
        fetch('/check_login?login=' + login.value)
            .then(response => {
                return response.json();
            })
            .then(data => {
                if (!data.valide) {
                    login.className = 'form-control is-invalid';
                    loginErr.innerText = data.msg;
                    login.setCustomValidity(data.msg);
                }
            })
    }
</script>
