<form method="post" action="<?= $router->pathFor('login') ?>">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Connexion</h5>
                </div>
                <div class="modal-body">
                    <?php if (isset($msg)) : ?>
                        <?= $msg ?>
                    <?php endif; ?>
                    <div class="form-group">
                        <label for="id">Email ou nom d'utilisateur</label>
                        <input required type="text" name="id" class="form-control" placeholder="Email ou nom d'utilisateur" id="id">
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input required type="password" name="password" class="form-control" placeholder="Mot de passe" id="password">
                    </div>
                    <div class="form-group">Vous n'avez pas encore de compte ? <a href="<?= $router->pathFor('register') ?>">S'inscrire</a></div>
                </div>
                <div class="modal-footer">
                    <?php if(pathinfo($_SERVER['REQUEST_URI'])['filename']=='moncompte') : ?>
                        <button type="button" class="btn btn-secondary" onclick="document.location='<?= $router->pathFor('home') ?>'">Annuler</button>
                    <?php else: ?>
                        <button type="button" class="btn btn-secondary" onclick="document.location='<?= $_SERVER['HTTP_REFERER']?>'">Annuler</button>
                    <?php endif; ?>
                    <button type="submit" class="btn btn-success">Connexion</button>
                </div>
            </div>
        </div>
</form>