<h1>Créez et ajoutez votre nouvel item à votre liste</h1><br>
<form method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label for="nom">Donnez un nom à l'item</label>
        <input required type="text" placeholder="Nom" name="nom" class="form-control" id="nom">
    </div>
    <div class="form-group">
        <label for="descr">Ajoutez une description à l'item</label>
        <textarea required class="form-control" placeholder="Description" name="descr" id="descr" rows="3"></textarea>
    </div>
    <div class="form-group">
        <label for="tarif">Indiquez le prix de l'item</label>
        <input required type="number" step="0.01" min="0" max="99999999.99" placeholder="Prix de l'item" name="tarif" class="form-control" id="tarif">
    </div>
    <div class="form-group">
        <div>
            <label for="img">Ajoutez une image à votre item</label>
            <a
                    data-trigger="focus"
                    role="button"
                    tabindex="0"
                    class="rounded-circle btn-sm btn-info text-white"
                    data-toggle="popover"
                    title="Informations pour l'image"
                    data-content="Formats acceptés : PNG, JPG, JPEG de taille inférieure ou égale à 10Mo. Si un autre format est sélectionné ou que l'image est trop volumineuse, aucune image ne sera importée.">
                i
            </a>
        </div>
        <input type="file" name="img" class="form-control-file" id="img">
    </div>
    <div class="form-group">
        <label for="url">Lien externe (Optionnel)</label>
        <input type="url" placeholder="Lien externe (Optionnel)" name="url" class="form-control" id="url">
    </div>

    <div class="modal-footer">
        <a href="<?= $router->pathFor('list', ['token' => $list->token])?>"><button type="button" class="btn btn-secondary">Annuler</button></a>
        <button type="submit" name="submit" class="btn btn-primary">Ajouter l'item</button>
    </div>
</form>

<script src="/public/js/jquery.slim.min.js"></script>
<script src="/public/js/popper.min.js"></script>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover()
    })
</script>