<h1>Créez votre nouvelle liste</h1><br>
<form method="POST" action="<?= $router->pathFor('newList') ?>">
    <div class="form-group">
        <label for="titre">Donnez un titre à la liste</label>
        <input required type="text" placeholder="Titre" name="titre" class="form-control" id="titre">
    </div>
    <div class="form-group">
        <label for="expiration">Indiquez une date d'expiration</label>
        <input required type="date" placeholder="Date expiration" name="expiration" class="form-control" id="expiration">
    </div>
    <div class="form-group">
        <label for="description">Ajoutez une description à la liste</label>
        <textarea required class="form-control" placeholder="Description" name="description" id="description" rows="3"></textarea>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="public" name="public">
        <label class="form-check-label" for="public">Public</label>
    </div>
    <div class="modal-footer">
        <a href="<?= $router->pathFor('publicLists') ?>"><button type="button" class="btn btn-secondary">Annuler</button></a>
        <button type="submit" class="btn btn-primary">Créer la liste</button>
    </div>
</form>