<h1>Créez votre nouvelle liste</h1><br>
<form method="POST" action="<?= $router->pathFor('postNewList') ?>">
    <div class="form-group">
        <label for="inputName">Donnez un titre à la liste</label>
        <input required type="text" placeholder="Titre" name="titre" class="form-control" id="titre">
    </div>
    <div class="form-group">
        <label for="inputName">Indiquez votre ID Utilisateur</label>
        <input required type="text" placeholder="ID Utilisateur" name="idUser" class="form-control" id="idUser">
    </div>
    <div class="form-group">
        <label for="inputName">Indiquez une date d'expiration</label>
        <input required type="date" placeholder="Date expiration" name="expiration" class="form-control" id="expiration">
    </div>
    <div class="form-group">
        <label for="textarea">Ajoutez une description à la liste</label>
        <textarea required class="form-control" placeholder="Description" name="description" id="description" rows="3"></textarea>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="document.location='<?= $router->pathFor('home') ?>';">Annuler</button>
        <button type="submit" class="btn btn-primary">Créer la liste</button>
    </div>
</form>