<h1>Listes publiques</h1>
<div class="body">
    <?php if ($lists->count() > 0) : ?>
        <?php foreach ($lists as $list) : ?>
            <div class="card mt-4 bg-light">
                <div class="card-body text-center pb-1">
                    <h1 class="card-title"><?= $list->titre ?></h1>
                    <p class="card-text lead"><?= $list->description ?></p>
                    <?php if (strtotime($list->expiration) > time()) : ?>
                        <p class="text-success">Liste valide jusqu'au : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
                    <?php else: ?>
                        <p class="text-danger">Expirée depuis le : <?= date("d/m/Y", strtotime($list->expiration)) ?></p>
                    <?php endif; ?>
                    <a href='<?= $router->pathFor('list', ['token' => $list->token]) ?>' class="stretched-link"></a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else : ?>
        <h3>Aucune liste publique en cours.</h3>
    <?php endif; ?>
</div>