<h1>Listes publiques</h1>
<div class="body mt-5">
    <table class="table table-bordered table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Description</th>
            <th scope="col">Expiration</th>
        </tr>
        </thead>

        <tbody>
        <?php foreach ($lists as $list) : ?>
            <?php if($list->public == 1) : ?>
                <tr onclick="document.location='<?= $router->pathFor('list', ['token' => $list->token]) ?>';">
                    <th scope="row"><?= $list->titre ?></th>
                    <td><?= $list->description ?></td>
                    <td><?= date("d/m/Y", strtotime($list->expiration)) ?></td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>