<form method="POST" action="<?= $router->pathFor('resetPassword') ?>">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Mot de passe perdu</h3>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="login">Email ou nom d'utilisateur</label>
                        <input required type="text" name="login" maxlength="100" class="form-control" placeholder="Email ou nom d'utilisateur" id="login" autofocus>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-secondary" href="<?= $router->pathFor('login') ?>" role="button">Annuler</a>
                    <button type="submit" class="btn btn-success">Réinitialiser</button>
                </div>
            </div>
        </div>
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
</form>